# Generated by Django 5.2.8 on 2025-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteEvent',
        ),
    ]
