# Generated by Django 5.2.8 on 2025-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_favorite_delete_favoriteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favorite',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='favorite',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favorite',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='favorite',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favorite',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='favorite',
            name='venue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
