# Generated by Django 5.2.8 on 2025-11-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0003_favorite_address_favorite_city_favorite_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='event_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
