# Generated by Django 5.2.8 on 2025-12-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0004_alter_favorite_address_alter_favorite_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
